const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const menu=q('.menu');if(menu)menu.onclick=()=>q('nav')?.classList.toggle('open');
const slides=[
{img:"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=88",k:"SOLUÇÕES EM CONSTRUÇÃO A SECO",t:'Ambientes que unem <em>qualidade, precisão</em> e acabamento.',p:"Forros, divisórias e drywall para projetos residenciais, comerciais e corporativos."},
{img:"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1800&q=88",k:"DIVISÓRIAS PARA AMBIENTES CORPORATIVOS",t:'Espaços que unem <em>organização</em> e produtividade.',p:"Soluções de divisórias para transformar e aproveitar melhor cada ambiente."},
{img:"https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1800&q=88",k:"FORROS E ACABAMENTOS",t:'Acabamento que valoriza <em>cada detalhe</em> do projeto.',p:"Soluções modernas para conforto, estética e desempenho do ambiente."}
];let si=0,timer;function showSlide(n){const hero=q('#home');if(!hero)return;si=(n+slides.length)%slides.length;const s=slides[si];hero.style.backgroundImage='url("'+s.img+'")';q('#heroKicker').textContent=s.k;q('#heroTitle').innerHTML=s.t;q('#heroText').textContent=s.p;qa('.dots button').forEach((d,i)=>d.classList.toggle('on',i===si));clearInterval(timer);timer=setInterval(()=>showSlide(si+1),6500)}if(q('#home')){showSlide(0);q('.slideArrow.next').onclick=()=>showSlide(si+1);q('.slideArrow.prev').onclick=()=>showSlide(si-1);qa('.dots button').forEach((d,i)=>d.onclick=()=>showSlide(i))}
const reviews=["Atendimento rápido e acabamento excelente.","Equipe organizada e muito cuidadosa com o ambiente.","O resultado ficou melhor do que imaginávamos.","Cumpriram o combinado e deixaram tudo bem acabado.","Ótima comunicação durante todo o projeto.","Serviço limpo, organizado e profissional.","Gostamos muito da qualidade das divisórias.","A reforma do escritório ficou moderna e funcional.","Atendimento atencioso desde o primeiro contato.","Execução rápida e com ótimo acabamento.","Forro muito bem instalado e equipe pontual.","Transformaram completamente nosso ambiente comercial.","Profissionais educados e muito organizados.","O drywall ficou perfeito e sem sujeira no final.","Excelente solução para dividir nosso escritório.","Gostei muito do cuidado com os detalhes.","Projeto bem executado do início ao fim.","A equipe explicou todas as etapas com clareza.","Resultado bonito e dentro do que combinamos.","Atendimento excelente e serviço muito caprichado.","As divisórias deram outra cara ao escritório.","Recomendo pelo profissionalismo e organização.","Tudo foi feito com bastante cuidado.","O acabamento ficou muito bonito.","Equipe comprometida e atendimento transparente.","Gostamos da agilidade na execução.","Solução prática e muito bem executada.","Nosso espaço ficou muito mais funcional.","Boa comunicação e excelente resultado.","Trabalho bem planejado e organizado.","Ficamos satisfeitos com o acabamento final.","Atendimento cordial e equipe preparada.","Serviço executado com muita atenção.","O novo forro valorizou bastante o ambiente.","Divisórias muito bem alinhadas e acabadas.","O projeto ficou exatamente como esperávamos.","Equipe pontual e muito profissional.","Reforma tranquila e sem complicações.","Gostamos da qualidade e da organização.","Ótima experiência do orçamento à entrega.","Ambiente renovado com excelente acabamento.","A equipe foi muito cuidadosa com nosso escritório.","Serviço de drywall muito bem executado.","Ficou moderno, limpo e funcional.","Atendimento próximo e resposta rápida.","Excelente trabalho em cada detalhe.","Execução eficiente e resultado profissional.","O espaço ficou muito melhor distribuído.","Qualidade perceptível no acabamento.","Voltaria a contratar para novos projetos."];
const names=["Ricardo Almeida","Fernanda Costa","Marcos Oliveira","Juliana Santos","Carlos Mendes","Patrícia Lima","André Souza","Camila Rocha","Eduardo Martins","Renata Alves"];let ri=0;function renderReviews(){const track=q('#reviewTrack');if(!track)return;track.innerHTML="";for(let j=0;j<6;j++){let i=(ri+j)%reviews.length;let a=document.createElement('article');a.innerHTML='<b>'+names[i%names.length]+'</b><small>Cliente demonstrativo</small><p>“'+reviews[i]+'”</p><em>★★★★★</em>';track.appendChild(a)}track.style.transform='translateX(0)'}if(q('#reviewTrack')){renderReviews();setInterval(()=>{const track=q('#reviewTrack');track.style.transform='translateX(-34%)';setTimeout(()=>{ri=(ri+3)%reviews.length;track.style.transition='none';renderReviews();requestAnimationFrame(()=>{track.style.transition='transform .65s ease'})},650)},7000)}
function saveLead(form){const d=Object.fromEntries(new FormData(form));d.fonte=document.referrer||'Acesso direto';d.pagina=location.href;d.utm_source=new URLSearchParams(location.search).get('utm_source')||'';d.utm_medium=new URLSearchParams(location.search).get('utm_medium')||'';d.utm_campaign=new URLSearchParams(location.search).get('utm_campaign')||'';const leads=JSON.parse(localStorage.getItem('carvix_leads')||'[]');leads.unshift({...d,data:new Date().toLocaleString('pt-BR')});localStorage.setItem('carvix_leads',JSON.stringify(leads))}
qa('.leadForm').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();saveLead(form);const btn=form.querySelector('.submitLead'),ok=form.querySelector('.formOk');btn.textContent='Mensagem enviada ✓';btn.disabled=true;ok.textContent='Recebemos sua solicitação.';form.reset();if(form.classList.contains('popupForm'))setTimeout(()=>{q('#quoteModal').classList.remove('open');setTimeout(()=>{btn.textContent='Enviar solicitação →';btn.disabled=false;ok.textContent=''},300)},1600)}));
const modal=q('#quoteModal');qa('.openQuote').forEach(b=>b.onclick=()=>modal?.classList.add('open'));q('.modalClose')?.addEventListener('click',()=>modal.classList.remove('open'));modal?.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
const chatBtn=q('#chatBtn'),chatBox=q('#chat');if(sessionStorage.getItem('carvix_chat_hidden')==='1'&&chatBtn)chatBtn.style.display='none';chatBtn?.addEventListener('click',()=>chatBox.style.display='block');q('#close')?.addEventListener('click',()=>{chatBox.style.display='none';chatBtn.style.display='none';sessionStorage.setItem('carvix_chat_hidden','1')});
const add=(t,c)=>{const p=document.createElement('p');p.className=c;p.textContent=t;q('#msgs').append(p);q('#msgs').scrollTop=9999};
const answer=t=>{t=t.toLowerCase();if(/orçamento|preço|valor/.test(t))return"Posso registrar seu pedido. Clique em 'Solicitar orçamento' ou informe qual serviço procura.";if(/serviço|servicos/.test(t))return"Trabalhamos com forros, divisórias, drywall e construção a seco.";if(/região|atendem|bairro/.test(t))return"Atendemos São Paulo e Guarulhos. Diga seu bairro para registrarmos sua consulta.";if(/forro/.test(t))return"Temos soluções em forros de gesso, PVC, modular e outros acabamentos.";if(/divis/.test(t))return"Trabalhamos com divisórias para escritórios, comércios e outros ambientes.";if(/drywall/.test(t))return"Drywall é uma solução versátil para paredes, fechamentos e reformas internas.";if(/atendente|whatsapp|humano/.test(t))return"Você pode falar com a equipe pelo WhatsApp: (11) 99277-9039.";return"Posso ajudar com orçamento, serviços, regiões atendidas, forros, divisórias ou drywall."};
q('#chatForm')?.addEventListener('submit',e=>{e.preventDefault();let t=q('#chatInput').value.trim();if(!t)return;add(t,'user');q('#chatInput').value='';setTimeout(()=>add(answer(t),'bot'),350)});qa('.quick button').forEach(b=>b.onclick=()=>{add(b.textContent,'user');setTimeout(()=>add(answer(b.textContent),'bot'),250)});
/* seletor PT/EN/ES - persiste no navegador */
const I18N={
en:{'Home':'Home','Sobre nós':'About us','Serviços':'Services','Áreas atendidas':'Service areas','Projetos':'Projects','Contato':'Contact','Solicitar orçamento':'Request a quote','Navegação':'Navigation','Atendimento':'Contact','Mais de 24 anos':'Over 24 years','de experiência':'of experience','Equipe especializada':'Specialized team','e comprometida':'and committed','Soluções sob medida':'Tailored solutions','para cada projeto':'for every project','Conte sobre seu projeto.':'Tell us about your project.','Enviar solicitação →':'Send request →'},
es:{'Home':'Inicio','Sobre nós':'Nosotros','Serviços':'Servicios','Áreas atendidas':'Áreas atendidas','Projetos':'Proyectos','Contato':'Contacto','Solicitar orçamento':'Solicitar presupuesto','Navegação':'Navegación','Atendimento':'Atención','Mais de 24 anos':'Más de 24 años','de experiência':'de experiencia','Equipe especializada':'Equipo especializado','e comprometida':'y comprometido','Soluções sob medida':'Soluciones a medida','para cada projeto':'para cada proyecto','Conte sobre seu projeto.':'Cuéntanos sobre tu proyecto.','Enviar solicitação →':'Enviar solicitud →'}
};
function addLang(){const nav=q('nav');if(!nav||q('.langSelect'))return;const s=document.createElement('select');s.className='langSelect';s.setAttribute('aria-label','Idioma');s.innerHTML='<option value="pt">🇧🇷 PT</option><option value="en">🇺🇸 EN</option><option value="es">🇪🇸 ES</option>';s.value=localStorage.getItem('carvix_lang')||'pt';const cta=nav.querySelector('.navcta');nav.insertBefore(s,cta||null);s.onchange=()=>{localStorage.setItem('carvix_lang',s.value);location.reload()}}
function translate(){const lang=localStorage.getItem('carvix_lang')||'pt';document.documentElement.lang=lang==='pt'?'pt-BR':lang;if(lang==='pt')return;const map=I18N[lang];document.querySelectorAll('a,b,small,strong,h2,button,span').forEach(el=>{if(el.children.length)return;const t=el.textContent.trim();if(map[t])el.textContent=map[t]});if(q('#heroKicker')){const s=slides[si];if(lang==='en'){q('#heroKicker').textContent='DRY CONSTRUCTION SOLUTIONS';q('#heroTitle').innerHTML='Spaces that combine <em>quality, precision</em> and finish.';q('#heroText').textContent='Ceilings, partitions and drywall for residential, commercial and corporate projects.'}if(lang==='es'){q('#heroKicker').textContent='SOLUCIONES EN CONSTRUCCIÓN EN SECO';q('#heroTitle').innerHTML='Ambientes que unen <em>calidad, precisión</em> y acabado.';q('#heroText').textContent='Cielorrasos, divisiones y drywall para proyectos residenciales, comerciales y corporativos.'}}}
addLang();translate();
