/* CARVIX i18n — PT/EN/ES, device detection + manual override */
(()=>{const supported=['pt','en','es'];const device=()=>{for(const x of (navigator.languages||[navigator.language||'pt'])){const l=String(x).toLowerCase().split('-')[0];if(supported.includes(l))return l}return'pt'};const current=()=>localStorage.getItem('carvix_lang')||device();
const D={
'Home':['Home','Home'],'Sobre nós':['About us','Sobre nosotros'],'Serviços':['Services','Servicios'],'Áreas atendidas':['Service areas','Zonas atendidas'],'Projetos':['Projects','Proyectos'],'Contato':['Contact','Contacto'],'Solicitar orçamento':['Request a quote','Solicitar presupuesto'],'Solicite um orçamento':['Request a quote','Solicita un presupuesto'],'Pedir orçamento':['Request a quote','Pedir presupuesto'],'Enviar solicitação →':['Send request →','Enviar solicitud →'],
'Navegação':['Navigation','Navegación'],'Atendimento':['Service','Atención'],'FALE CONOSCO':['CONTACT US','CONTÁCTANOS'],'SOLUÇÕES CARVIX':['CARVIX SOLUTIONS','SOLUCIONES CARVIX'],'REGIÕES':['REGIONS','REGIONES'],
'Soluções em forros, divisórias e drywall para projetos residenciais, comerciais e corporativos.':['Ceiling, partition and drywall solutions for residential, commercial and corporate projects.','Soluciones de cielorrasos, divisiones y drywall para proyectos residenciales, comerciales y corporativos.'],
'Construção a seco':['Dry construction','Construcción en seco'],'Forros':['Ceilings','Cielorrasos'],'Divisórias':['Partitions','Divisiones'],'Sancas e Molduras':['Coves and moldings','Molduras y cornisas'],
'Conte sobre seu projeto.':['Tell us about your project.','Cuéntanos sobre tu proyecto.'],'Envie seus dados para a equipe entender sua necessidade.':['Send your details so our team can understand your needs.','Envía tus datos para que nuestro equipo entienda tu necesidad.'],
'Seu nome':['Your name','Tu nombre'],'WhatsApp / telefone':['WhatsApp / phone','WhatsApp / teléfono'],'E-mail':['Email','Correo electrónico'],'Conte um pouco sobre o projeto':['Tell us a little about the project','Cuéntanos un poco sobre el proyecto'],
'Execução para diferentes necessidades':['Solutions for different needs','Ejecución para diferentes necesidades'],'Planejamento':['Planning','Planificación'],'Serviços relacionados':['Related services','Servicios relacionados'],'Dúvidas frequentes':['Frequently asked questions','Preguntas frecuentes'],
'Entendemos o ambiente, as medidas e o objetivo do projeto antes de definir a solução.':['We assess the space, measurements and project goals before defining the solution.','Evaluamos el ambiente, las medidas y el objetivo del proyecto antes de definir la solución.'],
'Projetos residenciais, comerciais e corporativos, com orçamento conforme medidas, materiais e condições da obra.':['Residential, commercial and corporate projects, quoted according to measurements, materials and site conditions.','Proyectos residenciales, comerciales y corporativos, presupuestados según medidas, materiales y condiciones de la obra.'],
'Como é feito o orçamento?':['How is the quote prepared?','¿Cómo se prepara el presupuesto?'],'A equipe avalia serviço, medidas, materiais e condições do local.':['Our team evaluates the service, measurements, materials and site conditions.','Nuestro equipo evalúa el servicio, las medidas, los materiales y las condiciones del lugar.'],
'Vocês atendem empresas e residências?':['Do you serve businesses and homes?','¿Atienden empresas y residencias?'],'Sim, a CARVIX trabalha com diferentes tipos de projeto.':['Yes. CARVIX works with different types of projects.','Sí. CARVIX trabaja con diferentes tipos de proyectos.'],
'Atendimento em São Paulo e Guarulhos':['Service in São Paulo and Guarulhos','Atención en São Paulo y Guarulhos'],'Principais áreas de atendimento':['Main service areas','Principales zonas de atención'],'Não encontrou seu bairro?':['Can’t find your neighborhood?','¿No encuentras tu barrio?'],'Entre em contato e informe o endereço da obra para confirmar o atendimento.':['Contact us with the project address to confirm service availability.','Contáctanos e informa la dirección de la obra para confirmar la atención.'],'Consultar atendimento':['Check service area','Consultar atención'],
'Zona Leste':['East Zone','Zona Este'],'Zona Norte':['North Zone','Zona Norte'],'Zona Sul':['South Zone','Zona Sur'],'Zona Oeste':['West Zone','Zona Oeste'],
'Mais de 24 anos':['Over 24 years','Más de 24 años'],'de experiência':['of experience','de experiencia'],'Atendimento em':['Service in','Atención en'],'São Paulo e região':['São Paulo and region','São Paulo y región'],'Equipe especializada':['Specialized team','Equipo especializado'],'e comprometida':['and committed','y comprometido'],'Soluções sob medida':['Tailored solutions','Soluciones a medida'],'para cada projeto':['for every project','para cada proyecto'],
'NOSSOS SERVIÇOS':['OUR SERVICES','NUESTROS SERVICIOS'],'Soluções completas para o seu projeto.':['Complete solutions for your project.','Soluciones completas para tu proyecto.'],'Construção a seco com praticidade e acabamento profissional.':['Practical dry construction with professional finishing.','Construcción en seco práctica y con acabado profesional.'],'Ver todos os serviços →':['View all services →','Ver todos los servicios →'],'Saiba mais →':['Learn more →','Más información →'],
'TRANSFORMAÇÃO CARVIX':['CARVIX TRANSFORMATION','TRANSFORMACIÓN CARVIX'],'Do ambiente bruto ao espaço pronto.':['From unfinished space to finished environment.','Del espacio en bruto al ambiente terminado.'],'Ver mais projetos →':['View more projects →','Ver más proyectos →'],'Falar com a equipe':['Talk to our team','Hablar con el equipo'],
'Por que escolher a CARVIX?':['Why choose CARVIX?','¿Por qué elegir CARVIX?'],'Qualidade garantida':['Quality assured','Calidad garantizada'],'em cada detalhe':['in every detail','en cada detalle'],'Prazos cumpridos':['Deadlines met','Plazos cumplidos'],'com organização':['with organization','con organización'],'Atendimento próximo':['Personal service','Atención cercana'],'e transparente':['and transparent','y transparente'],'Soluções personalizadas':['Custom solutions','Soluciones personalizadas'],'para cada necessidade':['for every need','para cada necesidad'],
'DEPOIMENTOS':['TESTIMONIALS','TESTIMONIOS'],'O que nossos clientes dizem.':['What our clients say.','Lo que dicen nuestros clientes.'],'Seu projeto começa aqui.':['Your project starts here.','Tu proyecto comienza aquí.'],
'Quero um orçamento':['I want a quote','Quiero un presupuesto'],'Quais são os serviços?':['What services do you offer?','¿Qué servicios ofrecen?'],'Atendem minha região?':['Do you serve my area?','¿Atienden mi zona?'],'Falar com um atendente':['Talk to an agent','Hablar con un agente'],'Assistente virtual':['Virtual assistant','Asistente virtual'],'Digite sua mensagem...':['Type your message...','Escribe tu mensaje...'],
'Atendente está digitando':['Agent is typing','El agente está escribiendo'],'Fazer ligação':['Make a call','Hacer una llamada'],'Enviar e-mail':['Send email','Enviar correo'],
'© 2026 CARVIX. Protótipo demonstrativo.':['© 2026 CARVIX. Demonstration prototype.','© 2026 CARVIX. Prototipo demostrativo.'],'Política de Privacidade · Termos de Uso':['Privacy Policy · Terms of Use','Política de Privacidad · Términos de Uso'],'Site desenvolvido e otimizado por':['Website developed and optimized by','Sitio desarrollado y optimizado por'],
'Divisórias sob medida para o projeto':['Custom partitions for your project','Divisiones a medida para tu proyecto'],'Melhor aproveitamento e organização dos ambientes.':['Better use and organization of spaces.','Mejor aprovechamiento y organización de los ambientes.'],'Soluções para escritórios, lojas, residências e empresas.':['Solutions for offices, stores, homes and businesses.','Soluciones para oficinas, tiendas, residencias y empresas.'],'Execução cuidadosa e acabamento profissional.':['Careful execution and professional finishing.','Ejecución cuidadosa y acabado profesional.'],'Atendimento em São Paulo e Guarulhos.':['Service in São Paulo and Guarulhos.','Atención en São Paulo y Guarulhos.'],'Quer dividir melhor o seu espaço?':['Want to divide your space more efficiently?','¿Quieres dividir mejor tu espacio?']
};
const regional={
'Zona Leste de São Paulo':['East Zone of São Paulo','Zona Este de São Paulo'],'Zona Norte de São Paulo':['North Zone of São Paulo','Zona Norte de São Paulo'],'Zona Sul de São Paulo':['South Zone of São Paulo','Zona Sur de São Paulo'],'Zona Oeste de São Paulo':['West Zone of São Paulo','Zona Oeste de São Paulo']
};
Object.assign(D,regional);
const originals=new WeakMap();function translateText(el,l){const idx=l==='en'?0:1;const walk=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n;while(n=walk.nextNode()){if(['SCRIPT','STYLE','NOSCRIPT'].includes(n.parentElement?.tagName))continue;if(!originals.has(n))originals.set(n,n.nodeValue);const base=originals.get(n),trim=base.trim();if(!trim)continue;const hit=D[trim];if(l==='pt')n.nodeValue=base;else if(hit)n.nodeValue=base.replace(trim,hit[idx]);}}
function attrs(l){const idx=l==='en'?0:1;document.querySelectorAll('[placeholder]').forEach(e=>{if(!e.dataset.ptPlaceholder)e.dataset.ptPlaceholder=e.getAttribute('placeholder');const p=e.dataset.ptPlaceholder;e.setAttribute('placeholder',l==='pt'?p:(D[p]?.[idx]||p))});document.querySelectorAll('[aria-label]').forEach(e=>{if(!e.dataset.ptAria)e.dataset.ptAria=e.getAttribute('aria-label');const p=e.dataset.ptAria;e.setAttribute('aria-label',l==='pt'?p:(D[p]?.[idx]||p))})}
function selector(l){let s=document.querySelector('.langSelect');const nav=document.querySelector('.top nav');if(!s&&nav){s=document.createElement('select');s.className='langSelect';s.setAttribute('aria-label','Idioma');s.innerHTML='<option value="pt">🇧🇷 PT</option><option value="en">🇺🇸 EN</option><option value="es">🇪🇸 ES</option>';const c=nav.querySelector('.navcta');nav.insertBefore(s,c||null)}if(s){s.value=l;s.onchange=()=>{localStorage.setItem('carvix_lang',s.value);apply(s.value,true)}}}
function chat(l){const idx=l==='en'?0:1,q=document.querySelectorAll('#chat .quick button');const keys=['Quero um orçamento','Quais são os serviços?','Atendem minha região?','Falar com um atendente'];q.forEach((b,i)=>{if(keys[i])b.textContent=l==='pt'?keys[i]:D[keys[i]][idx]});const first=document.querySelector('#msgs .bot');if(first&&!first.dataset.userConversation){const msg=l==='pt'?'Olá! 👋 Sou o assistente da CARVIX. Como posso ajudar?':l==='en'?'Hi! 👋 I’m the CARVIX assistant. How can I help?':'¡Hola! 👋 Soy el asistente de CARVIX. ¿Cómo puedo ayudarte?';const time=first.querySelector('.msgTime');first.childNodes[0].nodeValue=msg+(time?' ':'')}}function apply(l,manual=false){if(!supported.includes(l))l='pt';document.documentElement.lang=l==='pt'?'pt-BR':l==='en'?'en':'es';translateText(document.body,l);attrs(l);selector(l);chat(l);document.dispatchEvent(new CustomEvent('carvix:language',{detail:{lang:l,manual}}))}
function init(){const l=current();selector(l);apply(l);window.CARVIX_I18N={apply,set:l=>{localStorage.setItem('carvix_lang',l);apply(l,true)},get:current,device};}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();})();